
name: 'Scan for security vulnerabilities'

on:
  workflow_dispatch:
  pull_request:
    branch: [main,master,utama]

jobs:
  gitleaks:
    name: GitLeaks scan
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zricethezav/gitleaks
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Scan for leaks
      run: detect -v --source .


  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep
        env:
           SEMGREP_RULES: p/default # more at semgrep.dev/explore
  osv-scanner:
    runs-on: ubuntu-latest
    container: ghcr.io/google/osv-scanner
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Scan the code
      run: /osv-scanner --skip-git -r . || if [ $? -eq 128 ]; then true; else exit $?; fi
